version: '3.0'

services:
  airflow_database:
    image: amsterdam/postgres
    ports:
      - "5409:5432"
    container_name: airflow_database
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: airflow
      POSTGRES_USER: gob

  gobairflow:
    build: src
    container_name: gobairflow
    environment:
      MESSAGE_BROKER_ADDRESS: rabbitmq
    ports:
      - "8088:8088"

networks:
  default:
    external:
      name: gob-network
