FROM amsterdam/python:3.7-buster
MAINTAINER datapunt@amsterdam.nl

# Install required Python packages
COPY requirements.txt /app/
RUN pip3 install --no-cache-dir -r requirements.txt
RUN rm requirements.txt

COPY dags dags
COPY plugins plugins
COPY tests tests
COPY test.sh test.sh
COPY .flake8 .flake8
